### ISSUE TITLE
AttributeError: module 'attr' has no attribute 'setters'

### ISSUE THREAD

**Issue by maximmensah** [gleb-chipiga/aioairtable#2]
I tried to use this library to work with Airtable using the API, copied the code from the [main page of the project to Github](https://github.com/gleb-chipiga/aioairtable#using-aioairtable), after a second an error was raised:
`AttributeError: module 'attr' has no attribute 'setters'`

**Comment by maximmensah** [comment]
I also tried to install every existing version of attr but after checking none of the versions fixed this error.
Namely versions: 0.1.0, 0.2.0, 0.3.0, 0.3.1, 0.3.2

**Comment by gleb-chipiga** [comment]
The dependency on the `attrs` library has been removed.
