### ISSUE TITLE
Новые версии этой библиотеки всё ещё не доступны на pipy для установки

### ISSUE THREAD

**Issue by mensakh** [gleb-chipiga/aioairtable#3]
Я установил эту библиотеку используя pipy, после запуска кода из главной страницы проекта, заменив соответствующие данные на свои запуск не удался. У меня отобразилась ошибка:

`    records, offset = await table.list_records(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maksym-ub/aioairtable/lib/python3.11/site-packages/aioairtable/aioairtable.py", line 269, in list_records
    record_list: RecordList = await self._request('GET', url)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maksym-ub/aioairtable/lib/python3.11/site-packages/aioairtable/aioairtable.py", line 229, in _request
    return await self._base.request(method, url, json=json)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maksym-ub/aioairtable/lib/python3.11/site-packages/aioairtable/aioairtable.py", line 198, in request
    return await self._airtable.request(self._id, method, url, json=json)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maksym-ub/aioairtable/lib/python3.11/site-packages/backoff/_async.py", line 138, in retry
    wait = _init_wait_gen(wait_gen, wait_gen_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maksym-ub/aioairtable/lib/python3.11/site-packages/backoff/_common.py", line 30, in _init_wait_gen
    initialized.send(None)  # Initialize with an empty send
    ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/maksym-ub/aioairtable/lib/python3.11/site-packages/aioairtable/aioairtable.py", line 109, in backoff_wait_gen
    yield AT_WAIT + value
          ~~~~~~~~^~~~~~~
TypeError: unsupported operand type(s) for +: 'int' and 'NoneType'`

После недолгих разбирательств я обнаружил, что ранее установленная версия используя pipy это == 0.0.14.
В то время как последняя версия этой библиотеки на github является == 0.0.19.

Я попытался обновить снова библиотеку используя pip, так как возможно произошла ошибка, но это не помогло мне, последняя версия в pipy == 0.0.14.

**Comment by maximmensah** [comment]
Я также попытался установить переустановить эту библиотеку, заранее удалив прошлую версию с помощью pip.
Во второй раз я попытался установить напрямую из этого репозитория, используя команду:
`pip install git+https://github.com/gleb-chipiga/aioairtable.git#egg=aioairtable`

Но я также получил ошибку после отправки:
`Collecting aioairtable
  Cloning https://github.com/gleb-chipiga/aioairtable.git to /tmp/pip-install-lmcnke6g/aioairtable_d1ac674f031543df945b35b8cda891a1
  Running command git clone --filter=blob:none --quiet https://github.com/gleb-chipiga/aioairtable.git /tmp/pip-install-lmcnke6g/aioairtable_d1ac674f031543df945b35b8cda891a1
  Resolved https://github.com/gleb-chipiga/aioairtable.git to commit 16ac394c947b50483a997a50cbbcbe853f32b299
  Preparing metadata (setup.py) ... done
Requirement already satisfied: aiohttp in ./lib/python3.11/site-packages (from aioairtable) (3.9.1)
Requirement already satisfied: multidict in ./lib/python3.11/site-packages (from aioairtable) (6.0.4)
Requirement already satisfied: yarl in ./lib/python3.11/site-packages (from aioairtable) (1.9.4)
Requirement already satisfied: backoff>=2 in ./lib/python3.11/site-packages (from aioairtable) (2.2.1)
Requirement already satisfied: aiofreqlimit>=0.0.7 in ./lib/python3.11/site-packages (from aioairtable) (0.0.14)
INFO: pip is looking at multiple versions of aioairtable to determine which version is compatible with other requirements. This could take a while.
ERROR: Package 'aioairtable' requires a different Python: 3.11.0 not in '<3.11,>=3.8'`

**Comment by maximmensah** [comment]
Планируется ли выпустить в ближайшее время обновления, или дополнительное исправление которое позволит использовать эту библиотеку в python 3.11?
